/**
 * Intent parsing and response generation
 * NOW POWERED BY GENI BRAIN (context-aware, no hardcoded responses)
 */

import { generateResponse as geniBrainResponse } from './geni-brain';
import { moduleLogger } from '../lib/logger';

const log = moduleLogger('intent');

export interface Intent {
  intent: 'medication_confirm' | 'medication_query' | 'send_message' | 'call_contact' | 'general_query' | 'emergency';
  entities: {
    medicationName?: string;
    contactName?: string;
    message?: string;
    time?: string;
  };
  response: string;
}

/**
 * Simple intent detection (no AI needed for basic pattern matching)
 */
export async function parseIntent(userMessage: string): Promise<Intent> {
  const lowerMessage = userMessage.toLowerCase();
  
  // Emergency keywords
  if (lowerMessage.includes('help') || lowerMessage.includes('emergency') || lowerMessage.includes('fall')) {
    return {
      intent: 'emergency',
      entities: {},
      response: '', // Will be generated by GENI brain
    };
  }
  
  // Medication keywords
  if (lowerMessage.includes('pill') || lowerMessage.includes('medication') || lowerMessage.includes('medicine')) {
    if (lowerMessage.includes('took') || lowerMessage.includes('taken')) {
      return {
        intent: 'medication_confirm',
        entities: {},
        response: '', // GENI brain will generate contextual response
      };
    }
    return {
      intent: 'medication_query',
      entities: {},
      response: '',
    };
  }
  
  // Message/call keywords
  if (lowerMessage.includes('call') || lowerMessage.includes('phone')) {
    return {
      intent: 'call_contact',
      entities: {},
      response: '',
    };
  }
  
  if (lowerMessage.includes('message') || lowerMessage.includes('text')) {
    return {
      intent: 'send_message',
      entities: {},
      response: '',
    };
  }
  
  // Default to general query
  return {
    intent: 'general_query',
    entities: {},
    response: '',
  };
}

/**
 * Generate contextual response using GENI brain
 * NO HARDCODED RESPONSES - everything is context-aware
 */
export async function generateResponse(userMessage: string, conversationHistory: { role: 'user' | 'assistant'; text: string }[] = []): Promise<string> {
  try {
    log.info('🧠 Generating contextual response via GENI brain');
    const response = await geniBrainResponse(userMessage, conversationHistory);
    return response;
  } catch (error) {
    log.error({ err: error }, '❌ GENI brain error:');
    // Even fallback should be semi-contextual
    return "I'm having a bit of trouble thinking right now. Can you try again?";
  }
}
