"""
agents/captain.py — CAPTAIN: Full-stack builder.
Code execution, file ops, shell, architecture.
Phase 5+: send callback for WebSocket streaming.
Phase A: git context injection, edit_file tool.
Phase B: BuildSpec dual-ledger planning, before/after tool hooks, auto-DEVOPS review.
"""

import asyncio
import subprocess
from pathlib import Path
from typing import Optional

from pydantic import BaseModel

from agents.base import BaseAgent, SendFn
from config import Config
from memory.store import MemoryStore
from bus.message_bus import MessageBus
from bus.schema import AgentMessage, ChainPayload, HandoffPayload, ReviewPayload


# ── BuildSpec (Phase B: dual-ledger planning) ─────────────────────────────────

class FileSpec(BaseModel):
    path: str
    action: str   # "create" | "modify" | "delete"
    description: str


class BuildSpec(BaseModel):
    """
    Lightweight plan CAPTAIN checks against before its tool loop.
    Prevents scope creep on multi-file tasks. Generated by Haiku before the loop.
    Only triggered for tasks that mention multiple files or system-level changes.
    """
    files: list[FileSpec] = []
    steps: list[str] = []
    rationale: str = ""


# ── Git context helpers ───────────────────────────────────────────────────────

def _get_git_context(cwd: str | None = None) -> str:
    """
    Return git status --short + git diff --stat HEAD for the working directory.
    Injected into CAPTAIN's prompt so it's aware of what's changed.
    Falls back to empty string if not in a git repo.
    """
    try:
        status = subprocess.run(
            ["git", "status", "--short"],
            capture_output=True, text=True, timeout=5, cwd=cwd,
        ).stdout.strip()

        diff_stat = subprocess.run(
            ["git", "diff", "--stat", "HEAD"],
            capture_output=True, text=True, timeout=5, cwd=cwd,
        ).stdout.strip()

        parts = []
        if status:
            parts.append(f"git status:\n{status}")
        if diff_stat:
            parts.append(f"git diff --stat HEAD:\n{diff_stat}")
        return "\n\n".join(parts)[:2000]
    except Exception:
        return ""


class CaptainAgent(BaseAgent):
    name = "CAPTAIN"
    voice_style = "Focused. Clipped. Slightly faster pace. Minimal words."

    def __init__(self, config: Config, memory: MemoryStore, bus: MessageBus, user_registry=None) -> None:
        super().__init__(config, memory, bus, user_registry)
        self._model = config.SONNET_MODEL
        self._files_written: list[str] = []   # tracks write_file / edit_file calls this turn

    @property
    def base_identity(self) -> str:
        return (
            "You are CAPTAIN — full-stack builder for Praise Oyimi. "
            "You handle all code, builds, file operations, shell commands, and architecture.\n\n"
            "Voice: focused, clipped, slightly faster pace. Minimal words. "
            "Deliver working code, not explanations of what you will do.\n\n"
            "When writing code: no placeholder comments, no TODO stubs, no incomplete functions. "
            "Deliver finished, working implementations.\n\n"
            "Tool usage rules:\n"
            "- Always read a file before writing or editing it\n"
            "- Prefer edit_file over write_file for targeted changes (it enforces uniqueness)\n"
            "- Always show what code does before executing it\n"
            "- For destructive shell ops (rm, overwrite), state what will be deleted\n"
            "- Run tests after writing code when possible\n\n"
            "Languages: Python, TypeScript, JavaScript, Shell, SQL."
        )

    @property
    def allowed_tools(self) -> list[str]:
        from tools.registry import TOOL_REGISTRY
        return TOOL_REGISTRY["CAPTAIN"]

    def _execute_tool(self, tool_name: str, **kwargs) -> dict:
        result = self._call_tool("CAPTAIN", tool_name, **kwargs)
        # Track file writes for DEVOPS auto-review
        if tool_name in ("write_file", "edit_file") and isinstance(result, dict) and result.get("success"):
            path = result.get("path") or kwargs.get("path", "")
            if path:
                self._files_written.append(str(path))
        return result

    async def respond(self, user_text: str, send: SendFn = None) -> str:
        """
        CAPTAIN's full pipeline:
          1. Inject git context into the prompt
          2. QA loop (up to 3 attempts with Haiku-verified retry)
          3. Auto-dispatch DEVOPS review if files were written
        """
        from tools.qa import verify_output

        self._files_written = []   # reset per-turn tracker

        # ── Git context injection ─────────────────────────────────────────────
        git_ctx = await asyncio.to_thread(_get_git_context)
        if git_ctx:
            user_text = f"{user_text}\n\n---\n**Repo state:**\n{git_ctx}"

        history = await self.memory.get_recent_history(self._session_id, n=10) if self._session_id else []
        schemas = self._get_schemas("CAPTAIN")

        current_prompt = user_text
        response = ""

        # ── QA loop ───────────────────────────────────────────────────────────
        for attempt in range(1, 4):
            response = await self.tool_use_loop(
                user_text=current_prompt,
                tools=schemas,
                tool_executor=self._execute_tool,
                history=history,
                send=send,
            )

            try:
                qa = await verify_output(
                    user_text, response,
                    self.config.ANTHROPIC_API_KEY, self.config.HAIKU_MODEL,
                    attempt=attempt,
                )
            except Exception:
                break

            if qa.passed or attempt == 3:
                break

            if send:
                await send({
                    "type": "chunk", "agent": self.name,
                    "content": f"\n*[QA: {len(qa.issues)} issue(s) — retrying...]*\n",
                })
            current_prompt = f"{user_text}\n\n{qa.as_prompt_feedback()}"

        # ── Auto-DEVOPS review ────────────────────────────────────────────────
        if self._files_written:
            await self._trigger_devops_review(user_text, response)

        return response

    async def _trigger_devops_review(self, original_task: str, response: str) -> None:
        """Dispatch a code review request to DEVOPS after any file writes."""
        payload = ReviewPayload(
            code_summary=response[:300],
            files_changed=list(dict.fromkeys(self._files_written)),   # dedupe, preserve order
            task=original_task[:200],
            agent="CAPTAIN",
        )
        await self.dispatch_to("DEVOPS", payload, msg_type="request", priority=2)

    async def handle(self, msg: AgentMessage, send: SendFn = None) -> Optional[str]:
        if type(msg.payload).__name__ == "DispatchBriefPayload":
            return await self._handle_brief(msg.payload, send=send)
        """Handle bus messages — including SCOUT handoffs and legacy chain payloads."""
        if isinstance(msg.payload, HandoffPayload):
            task = (
                f"Task: {msg.payload.task}\n\n"
                f"Context from {msg.payload.from_agent}:\n{msg.payload.work_product}\n\n"
                f"Original request: {msg.payload.original_task}"
            )
            return await self.respond(task, send=send)

        if isinstance(msg.payload, ChainPayload):
            task = (
                f"Task: {msg.payload.next_action}\n\n"
                f"Context from {msg.payload.from_agent}:\n{msg.payload.work_product}\n\n"
                f"Original request: {msg.payload.original_task}"
            )
            return await self.respond(task, send=send)

        return await super().handle(msg, send=send)
